#!/bin/bash

# Test script for debug mode verification

echo "=== MorphProtocol Debug Mode Test ==="
echo ""
echo "This script demonstrates the debug feature that verifies"
echo "template encapsulation/decapsulation and obfuscation/deobfuscation."
echo ""
echo "To test:"
echo "1. Set DEBUG_MODE=true in your .env file"
echo "2. Start the server: npm run server"
echo "3. Start the client: npm run client <server_ip>:<port>:<user_id> <encryption_key>"
echo ""
echo "Expected behavior:"
echo "- Client sends 256 bytes of test data (0x00-0xFF pattern)"
echo "- Client logs: raw data, after obfuscation, after template encapsulation"
echo "- Server logs: after template decapsulation, after deobfuscation"
echo "- Server verifies data integrity and confirms all bytes match"
echo ""
echo "Example .env setting:"
echo "DEBUG_MODE=true"
echo ""
echo "Example client command:"
echo "npm run client 192.168.1.100:12301:testuser \"base64key:base64iv\""
echo ""
